stylelint-scss/stylelint-scss

src/rules/dollar-variable-pattern/README.md

I’m not sure how stringently you wish to adhere to the stylelint conventions in this repo, but we align the arrows in examples to *the beginning* of the things being highlighted because the ambiguity of not doing so got confusing on some rules.
The `dollar-variable-pattern` rule looks awesome btw. Everything else looks perfect! (except the deprecation of `stylelint-rule-tester`, but there’s another issue for that)
As this is a fledgling repo, I’ll try to pop in when I can if I spot something where I can pass on a lesson we learnt in building the rules for core. To save you guys making the same mistakes we did :)

Fix position of arrow in example

---

package.json

Now that stylelint recommends adding `stylelint-keyword` to NPM packages to aid in discoverability of stylelint plugins: http://stylelint.io/developer-guide/plugins/#sharing-plugins

Add `stylelint-plugin` keyword to `package.json`

---

src/rules/selector-no-redundant-nesting-selector/__tests__/index.js
src/rules/selector-no-redundant-nesting-selector/index.js

Fix false positives when `&` is used to combine classname from multiple parts or when BEM syntax is used.

selector-no-redundant-nesting-selector: fix false positives, fixes #32

---

CHANGELOG.md
CONTRIBUTING.md
src/index.js
src/rules/at-extend-no-missing-placeholder/index.js
src/rules/at-function-pattern/index.js
src/rules/at-import-no-partial-extension/index.js
src/rules/at-import-no-partial-leading-underscore/index.js
src/rules/at-mixin-no-argumentless-call-parentheses/index.js
src/rules/at-mixin-pattern/index.js
src/rules/dollar-variable-no-missing-interpolation/index.js
src/rules/dollar-variable-pattern/index.js
src/rules/percent-placeholder-pattern/index.js
src/rules/selector-no-redundant-nesting-selector/index.js
src/utils/index.js
src/utils/namespace.js

A quick fix to have stylelint correctly report `error` or `warning` instead of `ignore` for stylelint-scss rules. 
It seems that the plugin name has to match rule's name for everything to work. We have only been namespacing rule names when `createPlugin` gets called, which resulted in bug #33.
Would be nice to know if there is a cleaner way of fixing this than calling `namespace` function in each rule. /CC @davidtheclark @jeddy3 @ntwb @dryoma

Fix severity not working because ruleName is not prefixed, fixes #33

---

CHANGELOG.md
src/rules/selector-no-redundant-nesting-selector/__tests__/index.js
src/rules/selector-no-redundant-nesting-selector/index.js

`& #class {}`, `& %class {}`, `& [type="text"]` and a newline after `&` were still giving false negatives.
Continues to fix #32

selector-no-redundant-nesting-selector: fix false negatives

---

CHANGELOG.md
README.md
package.json
src/rules/index.js
src/rules/partial-no-import/README.md
src/rules/partial-no-import/__tests__/index.js
src/rules/partial-no-import/index.js

Implements #28 
Decided to change the name since it is partials that seem to be the *thing* (tha THIIIING!) here, not imports.
Was also happy to be able to peep a test example (not only scss code, but filenames have to be checked here) in stylelint repo :)

New rule: partial-no-import

---

CHANGELOG.md
README.md
src/rules/at-extend-no-missing-placeholder/README.md
src/rules/at-import-no-partial-extension/README.md
src/rules/at-import-no-partial-extension/__tests__/index.js
src/rules/at-import-no-partial-extension/index.js
src/rules/at-import-no-partial-leading-underscore/README.md
src/rules/at-import-partial-extension-blacklist/README.md
src/rules/at-import-partial-extension-blacklist/__tests__/index.js
src/rules/at-import-partial-extension-blacklist/index.js
src/rules/at-import-partial-extension-whitelist/README.md
src/rules/at-import-partial-extension-whitelist/__tests__/index.js
src/rules/at-import-partial-extension-whitelist/index.js
src/rules/at-mixin-no-argumentless-call-parentheses/README.md
src/rules/dollar-variable-no-missing-interpolation/README.md
src/rules/index.js
src/rules/percent-placeholder-pattern/README.md

Implements #41 
Two separate rules for extensions blacklist and whitelist, the old one gets deprecated (and to be removed in 2.0.0).
There is a problem though. Deprecation warning makes all the tests for `at-import-no-partial-extension` fail. Is there a more graceful way of giving such warnings?

New rules: at-import-partial-extension-blacklist, at-import-partial-extension-whitelist

---

src/rules/dollar-variable-no-missing-interpolation/index.js

My company is still on Node 4 (I am specifically running, Node 4.2.2 and NPM 2.15.0), and when I tried to use the `dollar-variable-no-missing-interpolation` rule, I received the following exception.
```
TypeError: vars.includes is not a function
at /Users/Developer/someproject/node_modules/stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.js:24:38
at /Users/Developer/someproject/node_modules/stylelint/node_modules/postcss/lib/container.js:94:28
at /Users/Developer/someproject/node_modules/stylelint/node_modules/postcss/lib/container.js:81:26
at Root.each (/Users/Developer/someproject/node_modules/stylelint/node_modules/postcss/lib/container.js:68:22)
at Root.walk (/Users/Developer/someproject/node_modules/stylelint/node_modules/postcss/lib/container.js:80:21)
at …
```

Fixes dollar-variable-no-missing-interpolation not working with older versions of Node.

---

CHANGELOG.md
README.md
src/rules/double-slash-comment-empty-line-before/README.md
src/rules/double-slash-comment-empty-line-before/__tests__/index.js
src/rules/double-slash-comment-empty-line-before/index.js
src/rules/double-slash-comment-inline/README.md
src/rules/double-slash-comment-inline/__tests__/index.js
src/rules/double-slash-comment-inline/index.js
src/rules/double-slash-comment-whitespace-inside/README.md
src/rules/double-slash-comment-whitespace-inside/__tests__/index.js
src/rules/double-slash-comment-whitespace-inside/index.js
src/rules/index.js
src/utils/__tests__/findCommentsInRaws.js
src/utils/__tests__/isInlineComment.js
src/utils/findCommentsInRaws.js
src/utils/index.js
src/utils/isInlineComment.js
src/utils/optionsHaveException.js
src/utils/optionsHaveIgnored.js

* `double-slash-comment-empty-line-before`
* `double-slash-comment-inline` (to force/forbid placing //-comments on the same line as other code)
* `double-slash-comment-whitespace-inside`
Implements #48 
PostCSS currently [drops some inline comments](https://github.com/postcss/postcss/issues/845#issuecomment-232306259), like in
```css
a, /* comment */ b { ... }
```
so in order to for the second and the third rules to work properly, without ignoring too much, the utility to parse (S)CSS code solely for comments were created.

Rules for //-comments

---

README.md
package.json
scripts/test-rule.js
scripts/test-util.js
src/utils/findCommentsInRaws.js

* Replace `babel-tape-runner` with the original `tape`.
`babel-tape-runner` uses `babel-polyfill`. So if a code has constructs like `Object.assign` which a JS interpreter (e.g. Node v0.12) doesn't, tests will run flawlessly, but actual code runs will throw.
`tape` can "require" external modules befor running tests now, so it's safer to use `tabe -r babel-register`. And I also love ditching big complex stuff for small vanilla stuff :)
The original issue: https://github.com/wavded/babel-tape-runner/issues/15 Thanks @olegskl for investigating.
* Update such Node v0.12 non-compatible code.
* Add [`tap-spec`](https://github.com/scottcorgan/tap-spec) for prettifying the output.
* Add helper scripts for easier test running
E.g. `npm run test-rule operator-no-unspaced` will run
``` …
```

Testing stuff

---

CHANGELOG.md
README.md
docs/examples/README.md
docs/examples/if-else.md
package.json
src/rules/at-else-closing-brace-newline-after/README.md
src/rules/at-else-closing-brace-newline-after/__tests__/index.js
src/rules/at-else-closing-brace-newline-after/index.js
src/rules/at-else-closing-brace-space-after/README.md
src/rules/at-else-closing-brace-space-after/__tests__/index.js
src/rules/at-else-closing-brace-space-after/index.js
src/rules/at-else-empty-line-before/README.md
src/rules/at-else-empty-line-before/__tests__/index.js
src/rules/at-else-empty-line-before/index.js
src/rules/at-if-closing-brace-newline-after/README.md
src/rules/at-if-closing-brace-newline-after/__tests__/index.js
src/rules/at-if-closing-brace-newline-after/index.js
src/rules/at-if-closing-brace-space-after/README.md
src/rules/at-if-closing-brace-space-after/__tests__/index.js
src/rules/at-if-closing-brace-space-after/index.js
src/rules/index.js

Implements #82 
These rules with the corresponding options are added (the reasoning and examples are in the issue discussion):
```
"at-if-closing-brace-newline-after": "always-last-in-chain"
"at-if-closing-brace-space-after": "always-intermediate"|"never-intermediate"
"at-else-closing-brace-newline-after": "always-last-in-chain"
"at-else-closing-brace-space-after": "always-intermediate"|"never-intermediate"
"at-else-empty-line-before": "never"
```
I also added the /docs folder, for now it only has [examples/if-else.md](https://github.com/kristerkari/stylelint-scss/blob/if-else-newlines/docs/examples/if-else.md).
There are still cases I belive are unresolved:
@ntwb Please see if the functionality that is complete so far works for you, and if there are any other things we need done.
cc. …

If else newlines

---

CHANGELOG.md
src/rules/at-if-closing-brace-newline-after/__tests__/index.js
src/rules/at-if-closing-brace-newline-after/index.js

Add support for `@elseif` for `at-if-closing-brace-newline-after` rule. [It works in Sass](https://github.com/sass/libsass/issues/1060) (but it's not documented).
fixes #107

at-if-closing-brace-newline-after: support @elseif

---

CHANGELOG.md
README.md
src/rules/at-rule-no-unknown/README.md
src/rules/at-rule-no-unknown/__tests__/index.js
src/rules/at-rule-no-unknown/index.js
src/rules/index.js

Addresses #86 by adding a "new" rule extending stylelint's `at-rule-no-unknown` with a built-in list of exceptions including at-rules supported by Sass/SCSS.

Add rule: at-rule-no-unknown

---

package-lock.json
package.json
src/rules/at-rule-no-unknown/README.md
src/rules/at-rule-no-unknown/__tests__/index.js
src/utils/isStandardRule.js
src/utils/isStandardSelector.js
src/utils/isStandardSyntaxProperty.js
yarn.lock

Notes:
1. Support npm@5 (add `package-lock.json`)
2. We change logic `ignore*` (see https://github.com/stylelint/stylelint/pull/2709)
3. Use `stylelint` build-in `isStandardSyntax*` (less code - best support)
4. Remove `replace` package (is not used anywhere)

Feature: migrate to `stylelint@8.0.0`.

---

CHANGELOG.md
src/rules/dollar-variable-colon-newline-after/__tests__/index.js
src/rules/dollar-variable-colon-newline-after/index.js

dollar-variable-colon-newline-after: allow multiline vars with "always"

---

src/rules/dollar-variable-colon-newline-after/__tests__/index.js
src/rules/dollar-variable-colon-newline-after/index.js

See discussion in: https://github.com/kristerkari/stylelint-scss/issues/172#issuecomment-369716880
Fixes #172
Please review this @levacic @sindresorhus @AndyOGo

dollar-variable-colon-newline-after: always allow multiline vars with parens

---

package-lock.json
package.json
src/rules/double-slash-comment-inline/__tests__/index.js
src/rules/double-slash-comment-inline/index.js
src/rules/double-slash-comment-whitespace-inside/__tests__/index.js
src/rules/double-slash-comment-whitespace-inside/index.js
src/rules/operator-no-unspaced/__tests__/index.js
src/rules/operator-no-unspaced/index.js
src/utils/eachRoot.js
src/utils/index.js
src/utils/sassValueParser/index.js

In stylelint we starting support non css syntax, i.e. `postcss-html`(vue and other html based syntaxes)/`postcss-markdown`/`postcss-css-in-js` to allow linting styles in these formats. Some rules require modification. After release `stylelint@9.3.0` it is possible to add tests on this changes.
Ref: https://github.com/stylelint/stylelint/blob/94174973b2bdb397830deae804ca2f5d46b19ab4/docs/user-guide/css-processors.md
Same PR in stylelint: https://github.com/stylelint/stylelint/pull/3367
Briefly: we migrate on `postcss-syntax` what change `postcss-*` parser based on extension and support non css syntaxes

fix: compatibility with non css syntaxes

---

CONTRIBUTING.md

The links were not rendering correctly because of the extra spaces.

Fix link markup in contribution guidelines

---

src/rules/at-function-named-arguments/__tests__/index.js
src/utils/__tests__/parseFunctionArguments.js
src/utils/parseFunctionArguments.js

When `at-function-named-arguments` is enabled, stylelint crashes when the rule attempts to parse function calls that have a trailing comma (has been [part of Sass since ± 2016](https://github.com/sass/libsass/issues/2070)). For example:
```scss
.b {
border: reset(
$value: 40px,
);
}
```
This will cause the following error:
```
TypeError: Cannot read property 'key' of undefined
98 |             case "always": {
>  99 |               if (arg.key && isScssVarRegExp.test(arg.key)) {
|                                                    ^
100 |                 return;
101 |               }
at src/rules/at-function-named-arguments/index.js:99:52
[...]
```
---
The error is caused by `groupByKeyValue` of  `parseFunctionArguments`, which creates an empty group when seeing the comma. It seems like a …

Fix crash when at-function-named-arguments encounters trailing commas in function calls

---

src/rules/at-function-parentheses-space-before/__tests__/index.js
src/rules/at-function-parentheses-space-before/index.js
src/rules/at-mixin-parentheses-space-before/__tests__/index.js
src/rules/at-mixin-parentheses-space-before/index.js

Current rules won’t fix cases where function or mixin name uses hyphens, e.g.:
```scss
@function first-column-percentage-width($ratio) {
@return percentage(nth($ratio, 1) / (nth($ratio, 2) - nth($ratio, 1)));
}
```

Account for hyphens in function and mixin names

---

README.md
src/rules/at-else-empty-line-before/README.md
src/rules/at-mixin-argumentless-call-parentheses/README.md
src/rules/at-mixin-argumentless-call-parentheses/__tests__/index.js
src/rules/at-mixin-argumentless-call-parentheses/index.js

This PR adds fix functionality to `at-mixin-argumentless-call-parentheses`. There is one problem, though: it should also depend on `at-mixin-parentheses-space-before` rule for spacing but currently there is no way to check against other rule. There is [`stylelint.utils.checkAgainstRule`](https://stylelint.io/developer-guide/plugins/#stylelintutilscheckagainstrule) helper utility, but it doesn’t know about other SCSS rules since [Jest Stylelint setup works only for one rule](https://github.com/kristerkari/stylelint-scss/blob/69a4c625009fde200c54556d11a3f18fa34cf29c/jest-setup.js#L23-L29). Does it make sense to upgrade Jest config to allow additional configuration to account for these changes?

Initial work on "at-mixin-argumentless-call-parentheses" fix

---

CHANGELOG.md
src/rules/at-function-named-arguments/__tests__/index.js
src/rules/at-function-named-arguments/index.js

at-function-named-arguments: correctly parse functions inside Sass maps

---

src/rules/index.js
src/rules/selector-nest-combinators/README.md
src/rules/selector-nest-combinators/__tests__/index.js
src/rules/selector-nest-combinators/index.js

Added a new rule called `selector-nest-combinator` as well as a README and tests.
Currently the only options are `always` and `never`. This rule may be more useful with more options, such as `pseudo-only` or exceptions such as `attribute`.

[#197] - New rule to enforce nesting

---

src/rules/selector-nest-combinators/__tests__/index.js
src/rules/selector-nest-combinators/index.js

Handle interpolation in selector-nest-combinators

---

.travis.yml
appveyor.yml
package-lock.json
package.json
yarn.lock

- Removed: node.js 6.x support
- Update peer dependency stylelint v10.0.0
Resolve #316
Resolve #315

Support stylelint v10

---

src/rules/double-slash-comment-empty-line-before/__tests__/index.js
src/rules/double-slash-comment-empty-line-before/index.js
src/utils/__tests__/addEmptyLineBefore.test.js
src/utils/__tests__/removeEmptyLineBefore.test.js
src/utils/addEmptyLineBefore.js
src/utils/index.js
src/utils/removeEmptyLinesBefore.js

double-slash-comment-empty-line-before: bug with "never" option autofix

---

src/rules/function-unquote-no-unquoted-strings-inside/README.md
src/rules/function-unquote-no-unquoted-strings-inside/__tests__/index.js
src/rules/function-unquote-no-unquoted-strings-inside/index.js
src/rules/index.js

The sass/linter repo has a [suggestion for a rule](https://github.com/sass/linter/issues/37) that would alert users using unquote on an already unquoted string.
This rules finds unnecessary calls to `unquote()` and removes the call to `unquote()` if autofixing is enabled.
(This is very much in line with #324)

Lint rule to check for unquote() receiving an unquoted string

---

src/rules/at-else-empty-line-before/index.js
src/rules/dollar-variable-empty-line-before/index.js

"Unexpected" was typod as "unxpected" in at-else-empty-line-before and
dollar-variable-empty-line-before messages.

Fix "unxpected" typo in error messages

---

README.md
src/rules/index.js
src/rules/selector-no-union-class-name/README.md
src/rules/selector-no-union-class-name/__tests__/index.js
src/rules/selector-no-union-class-name/index.js

Added new rule to fix https://github.com/kristerkari/stylelint-scss/issues/314.
This rule disallow to union class name like [this](https://github.com/kristerkari/stylelint-scss/pull/338/files#diff-216b2f4a7cbff3ec0d33ead1e8ee872dR35).

[FIxed:314] add rule `selector-no-union-class-name`

---

src/rules/selector-no-union-class-name/__tests__/index.js
src/rules/selector-no-union-class-name/index.js

Fix selector-no-union-class-name throwing when parent.selector is undefined

---

CHANGELOG.md
src/rules/map-keys-quotes/__tests__/index.js
src/rules/map-keys-quotes/index.js

Fixes #348
ping @certainlyakey @rambleraptor @nex3

map-keys-quotes: don't require numbers to be quoted

---

src/rules/declaration-nested-properties/__tests__/index.js
src/rules/selector-nest-combinators/__tests__/index.js
src/rules/selector-nest-combinators/index.js

Fixes #359
@JounQin please review

Fix selector-nest-combinators throwing an error when using nested props

---

src/rules/at-if-no-null/README.md
src/rules/at-if-no-null/__tests__/index.js
src/rules/at-if-no-null/index.js
src/rules/index.js

The [sass/linter](https://github.com/sass/linter/blob/master/lib/src/rules/use_falsey_null.dart) project had a rule to check for using `== null` or `!= null` inside @if statements.
This rule replicates that.

New rule: `at-if-no-null`

---

src/rules/at-import-partial-extension/README.md
src/rules/at-import-partial-extension/__tests__/index.js
src/rules/at-import-partial-extension/index.js
src/rules/index.js

Fixes #349
@amstiel @nex3 please review

Add at-import-partial-extension rule

---

src/rules/dimension-no-non-numeric-values/__tests__/index.js
src/rules/dimension-no-non-numeric-values/index.js

Fix following issues related to the `dimension-no-non-numeric-values` rule:
- Rejected message was throwing an error because it was called without the unit.
- Change highlighted error to point to the unit that is used with the interpolation, instead of it pointing to the property name. That makes much more sense if you are using this rule with CSS shorthand properties.
Fixes #363
Please review @rambleraptor @fuhlig

Fix error reporting for dimension-no-non-numeric-values

---

README.md
src/rules/index.js
src/rules/no-duplicate-mixins/README.md
src/rules/no-duplicate-mixins/__tests__/index.js
src/rules/no-duplicate-mixins/index.js
src/utils/atRuleBaseName.js
src/utils/index.js

This adds a `no-duplicate-mixins` rule that checks wether a stylesheet contains multiple declarations for the same mixin.
It is heavily inspired by the `no-duplicate-dollar-variables` rule.

Add no-duplicate-mixins rule

---

CHANGELOG.md
src/rules/map-keys-quotes/__tests__/index.js
src/rules/map-keys-quotes/index.js

map-keys-quotes: ignore math operators inside map values

---

src/utils/sassValueParser/index.js

`/` is already present in the character list.
Found with https://lgtm.com/projects/g/kristerkari/stylelint-scss/alerts?mode=list

sassValueParser/index.js: fix duplicate character in regex

---

src/utils/sassValueParser/index.js

I assume this was meant to be `A-Z`. If not then `_` is duplicate and we should remove it.
Found with https://lgtm.com/projects/g/kristerkari/stylelint-scss/alerts?mode=list

sassValueParser/index.js: fix wrong regex

---

package.json

Single quotes don't work properly in all shells.

package.json: double quote globs

---

src/rules/at-rule-no-unknown/__tests__/index.js
src/rules/at-rule-no-unknown/index.js

This PR fixes a bug in `at-rule-no-unknown`. `utils.checkAgainstRule` and `root.walkAtRules` are both called, and both loop over rules. This leads to `n^2` warnings rather than `n`.
For example, linting the file with two unknowns:
```css
@foo { }
@bar { }
```
Leads to four warnings running:
```txt
1:1  Unexpected unknown at-rule "@foo" (at-rule-no-unknown)
1:1  Unexpected unknown at-rule "@foo" (at-rule-no-unknown)
2:1  Unexpected unknown at-rule "@bar" (at-rule-no-unknown)  
2:1  Unexpected unknown at-rule "@bar" (at-rule-no-unknown)
```
I wasn't sure how to add tests for this since it never failed any to begin with. If updated tests are required, I would appreciate any pointers!

at-rule-no-unknown: remove duplicate looping logic

---

README.md
package-lock.json
package.json
src/utils/__tests__/isCustomPropertySet.test.js
src/utils/isCustomPropertySet.js
src/utils/isStandardRule.js

Requires #427 merged and tests to be fixed
Closes #433

Update stylelint to v13.0.0

---

jest-setup.js
package-lock.json
package.json
src/rules/at-else-closing-brace-newline-after/index.js
src/rules/at-function-named-arguments/index.js
src/rules/at-function-pattern/index.js
src/rules/at-if-closing-brace-newline-after/index.js
src/rules/at-import-partial-extension-blacklist/index.js
src/rules/at-import-partial-extension-whitelist/index.js
src/rules/at-mixin-pattern/index.js
src/rules/at-rule-no-unknown/index.js
src/rules/dollar-variable-colon-newline-after/index.js
src/rules/dollar-variable-empty-line-before/index.js
src/rules/dollar-variable-pattern/index.js
src/rules/no-duplicate-dollar-variables/index.js
src/rules/percent-placeholder-pattern/index.js
src/utils/isCustomPropertySet.js
src/utils/isStandardRule.js

Since stylelint is using this, it should be already cached.
Requires #428 and then a rebase

Switch back to using the lodash package.

---

src/rules/operator-no-unspaced/__tests__/index.js
src/rules/operator-no-unspaced/index.js

operator-no-unspaced: ignore operators inside @at-root

---

src/rules/media-feature-value-dollar-variable/README.md
src/rules/media-feature-value-dollar-variable/__tests__/index.js
src/rules/media-feature-value-dollar-variable/index.js

Fix #438
CSS media features also have some keyword values, like `none`, `fine`, `srgb`. Usually you should not define a variable for them which is just overkill.
```scss
// valid
@media screen and (pointer: fine) and (min-width: $breakpoint) {}
```
In my project, I want all media feature use variables for sizes. But I don't want to define variables for standard keywords like `fine`, `dark`.

Allow keyword value in any conditions

---

src/rules/no-duplicate-dollar-variables/README.md
src/rules/no-duplicate-dollar-variables/__tests__/index.js
src/rules/no-duplicate-dollar-variables/index.js

no-duplicate-dollar-variables: allow dup vars in unrelated scopes

---

src/rules/double-slash-comment-empty-line-before/README.md
src/rules/double-slash-comment-empty-line-before/__tests__/index.js
src/rules/double-slash-comment-empty-line-before/index.js

double-slash-comment-empty-line-before: add except:"inside-blocks", ignore:"inside-blocks"

---

README.md
src/rules/dollar-variable-empty-line-after/README.md
src/rules/dollar-variable-empty-line-after/__tests__/index.js
src/rules/dollar-variable-empty-line-after/index.js
src/rules/index.js

This adds a `dollar-variable-empty-line-after` rule.
It's very much inspired by `dollar-variable-empty-line-before`.
It checks that you always (or never) have an empty line after variables. You can add exceptions for "last-nested", "before-comment" and "before-dollar-variable", and ignore "before-comment" and "inside-single-line-block".
Apart [this other pull request](https://github.com/kristerkari/stylelint-scss/pull/372) I made a few minutes ago, this is my first contribution to `stylelint-scss` ... Let me know if there's anything I need to do differently :) Thanks

Rule for dollar-variable-empty-line-after

---

README.md
src/rules/dollar-variable-first-in-block/README.md
src/rules/dollar-variable-first-in-block/__tests__/index.js
src/rules/dollar-variable-first-in-block/index.js
src/rules/index.js

This adds a `dollar-variable-first-in-block` rule that checks if variables are put first in a block (root and rules).
It can be set to ignore comments and imports, and make exceptions when variables are placed in root or inside an at-rule, function, mixin, if/else or for/each/while-loops.
This is my first contribution to `stylelint-scss` ... Please don't hesitate to let me know, if I'm doing anything wrong :)

Added rule for dollar-variable-first-in-block

---

src/rules/function-color-relative/__tests__/index.js
src/rules/function-color-relative/index.js
src/rules/function-quote-no-quoted-strings-inside/__tests__/index.js
src/rules/function-quote-no-quoted-strings-inside/index.js
src/rules/function-unquote-no-unquoted-strings-inside/__tests__/index.js
src/rules/function-unquote-no-unquoted-strings-inside/index.js
src/rules/no-global-function-names/__tests__/index.js
src/rules/no-global-function-names/index.js

The rules belonging to the group `function` were missing the index setting, which caused the warning to highlight the CSS property instead of the function name.

Fix index for function-* rules

---

src/rules/function-color-relative/README.md

"scalar-color" should be "scale-color" in "function-color-relative" example

---

src/rules/operator-no-unspaced/__tests__/index.js
src/utils/sassValueParser/index.js

fixes signed parameter in a function call inside interpolation (#450)

operator-no-unspaced: fix signed parameter (#450)

---

.github/workflows/test.yml
jest-setup.js
package-lock.json
package.json
src/rules/at-each-key-value-single-line/index.js
src/rules/at-if-closing-brace-newline-after/index.js
src/rules/at-rule-conditional-no-parentheses/index.js
src/rules/at-rule-no-unknown/__tests__/index.js
src/rules/at-rule-no-unknown/index.js
src/rules/dollar-variable-empty-line-after/index.js
src/rules/no-global-function-names/index.js
src/rules/partial-no-import/__tests__/index.js
src/utils/findCommentsInRaws.js
src/utils/isInlineComment.js
src/utils/whitespaceChecker.js

@kristerkari feel free to push to this branch before merging to fix the remaining lint issues and ping me. Note that this PR targets the v4 branch.
Non-whitespace diff: <https://github.com/kristerkari/stylelint-scss/pull/469/files?w=1>

Update devDependencies and drop Node.js < 10 support

---

src/rules/comment-no-loud/__tests__/index.js
src/rules/comment-no-loud/index.js

Addresses https://github.com/kristerkari/stylelint-scss/issues/439
This changes the approach to looking up comments for the comment-no-loud
rule. This rule had an issue where it would only identify comments if
they were the first node within an SCSS file.
Previously this check matched a regex against `source.input.css` of the
comment node. `source.input.css` is actually the full input of the
source file and not the input of the node (as I imagine was expected
when this was initially authored). This meant that only comments that
were not preceded by any other nodes matched the rule. The tests all
succeeded for this as they all checked against the first node.
This new approach instead takes the source input and splits into an array
based on a `\n` separator. It then looks up the first line …

Fix comment-no-load only covering first line

---

README.md
src/rules/at-rule-conditional-no-parentheses/README.md

It's not documented, but the rule seems to have the ability of autofix.

Fix lack of note about autofix for at-rule-conditional-no-parentheses rule

---

README.md

These rules will help users getting rid of style-lint warnings for SCSS scripts.
We can assume that plugin users will use SCSS therefore it might make sense to have these rules as part of the installation process.

Add recommended rules to installation part of README

---

src/rules/selector-nest-combinators/__tests__/index.js
src/rules/selector-nest-combinators/index.js

selector-nest-combinators: fix error being thrown with nested combinators

---

src/rules/dollar-variable-first-in-block/README.md
src/rules/dollar-variable-first-in-block/__tests__/index.js
src/rules/dollar-variable-first-in-block/index.js

Improve the `dollar-variable-first-in-block` rule's `ignore: ["imports"]` option so that it also ignores `@use` and `@forward`.
fixes #517
ping @EvgenyOrekhov

dollar-variable-first-in-block: support ignoring @use and @forward

---

src/rules/comment-no-empty/README.md

Describe core rule `comment-no-empty`

---

src/rules/at-rule-no-unknown/__tests__/index.js
src/rules/at-rule-no-unknown/index.js

Fix duplicate rule names in `at-rule-no-unknown` message

---

src/rules/comment-no-empty/__tests__/index.js
src/rules/comment-no-empty/index.js

This change aims to respect the message of the stylelint's core rule [`comment-no-empty`](https://github.com/stylelint/stylelint/blob/a8042e7192cad993081cf982901948dbd5004048/lib/rules/comment-no-empty/index.js#L12).
Because the `scss/comment-no-empty` is essentially an extension of the core rule.
Related to #481 and #483

Unify messages for `comment-no-empty` and `scss/comment-no-empty`

---

src/rules/no-global-function-names/__tests__/index.js
src/rules/no-global-function-names/index.js

This PR adds following adjustments:
* Interpolation handling
* [postcss-value-parser](https://github.com/TrySound/postcss-value-parser) doesn’t have interpolation handling so this is achieved with very crude implementation by stripping `#{` from start of `node.value`. I’ve opened [PR](https://github.com/TrySound/postcss-value-parser/pull/78) for this but it doesn’t seem there is any interest to implement this. [postcss-values-parser](https://github.com/shellscape/postcss-values-parser) handles this so maybe consider switching to this at later date?
* Some color functions have mapping to completely new syntax so I’ve made rule mappings for that. There is a list with recommendations: https://sass-lang.com/documentation/modules/color

Add adjustments for `no-global-function-names`

---

src/rules/no-global-function-names/__tests__/index.js
src/rules/no-global-function-names/index.js

The Sass functions should indeed be migrated to the sass:math module. But min() and max() can also be the CSS functions (and with first-class calc in Sass, it will parse it as a calculation if possible).
Closes #560
Closes #562
Closes #486

Allow using the CSS min and max calculations and the CSS filter functions

---

src/utils/parseSelector.js

in the Stylelint source code, it use processSync.
process() returns a Promise but it's not handled properly.

fix: use processSync

---

README.md
src/rules/at-each-key-value-single-line/README.md
src/rules/at-each-key-value-single-line/__tests__/index.js
src/rules/at-each-key-value-single-line/index.js
src/utils/__tests__/moduleNamespace.test.js
src/utils/index.js
src/utils/moduleNamespace.js

The `at-each-key-value-single-line` rule does not report an error when set to `true` and using sass modules.
This should fail but it doesn't:
```scss
@use 'sass:map';
$font-weights: ("regular": 400, "medium": 500, "bold": 700);
@each $key in map.keys($font-weights) {
$value: map.get($font-weights, $key);
}
```
This pull request changes the rule to take the use of sass modules into account.

Consider the use of sass modules in at-each-key-value-single-line rule

---

package-lock.json
package.json
src/rules/function-no-unknown/README.md
src/rules/function-no-unknown/__tests__/index.js
src/rules/function-no-unknown/index.js
src/rules/index.js
src/utils/functions.js
src/utils/index.js

Add `scss/function-no-unknown` rule

---

src/rules/at-else-closing-brace-newline-after/README.md
src/rules/at-else-closing-brace-space-after/README.md
src/rules/at-else-empty-line-before/README.md
src/rules/at-else-if-parentheses-space-before/README.md
src/rules/at-function-parentheses-space-before/README.md
src/rules/at-if-closing-brace-newline-after/README.md
src/rules/at-if-closing-brace-space-after/README.md
src/rules/at-mixin-argumentless-call-parentheses/README.md
src/rules/at-mixin-parentheses-space-before/README.md
src/rules/at-rule-conditional-no-parentheses/README.md
src/rules/dollar-variable-colon-newline-after/README.md
src/rules/dollar-variable-colon-space-after/README.md
src/rules/dollar-variable-colon-space-before/README.md
src/rules/dollar-variable-empty-line-after/README.md
src/rules/dollar-variable-empty-line-before/README.md
src/rules/double-slash-comment-empty-line-before/README.md

For example, the doc of a core rule `alpha-value-notation` is helpful.
See https://stylelint.io/user-guide/rules/list/alpha-value-notation

Fix `--fix` option link on each rule doc

---

README.md
src/rules/at-import-partial-extension/README.md
src/rules/at-import-partial-extension/__tests__/index.js
src/rules/at-import-partial-extension/index.js

This PR adds the *autofix* support to the `scss/at-import-partial-extension` rule only when the `"never"` option is given.
I believe we cannot support autofix when `"always"` is given because it's impossible to determine file extensions to be added.

Add `at-import-partial-extension` autofix only when `"never"`

---

src/rules/at-function-pattern/__tests__/index.js
src/rules/at-function-pattern/index.js
src/rules/at-mixin-pattern/__tests__/index.js
src/rules/at-mixin-pattern/index.js

Hi, first contrib here.
I noticed the `at-function-pattern` and `at-mixin-pattern` rules spit out warnings with a range over the *entire* at-rule block as the "problem area", which of course doesn't make sense when it's just the name that's the issue.
Not at all familiar with the codebase and I just wanted to slap a quick fix on it if I could, best I was able to do was limiting it to one line only.
Before:
After:

Fix at-rule pattern warnings to range only one line

---

src/rules/at-import-partial-extension/__tests__/index.js
src/rules/at-import-partial-extension/index.js

Hi, my first contrib here. 👋
While fixing a large codebase I noticed the `at-import-partial-extension` fixer incorrectly fixed certain files when they have `.scss` in their filename. (example: `component.scss-theme.scss`)
---
**currently**:
`at-import-partial-extension`'s fixer incorrectly replaced all `.scss` occurences in a filename.
```diff
- @import "component.scss-theme.scss";
+ @import "component-theme";
```
**expected**:
`at-import-partial-extension`'s fixer should only replace the `.scss` extension (not when `.scss` is used in the filename itself)
```diff
- @import "component.scss-theme.scss";
+ @import "component.scss-theme";
```

bugfix(at-import-partial-extension): fixer incorrectly replaces filename

---

.husky/pre-commit
package.json

Bumping husky from v4 to v8 broke husky.
Introduced in change: https://github.com/stylelint-scss/stylelint-scss/pull/627
Followed migration guide: https://github.com/typicode/husky-4-to-8
Side note: Prettier2 upgrade (https://github.com/stylelint-scss/stylelint-scss/pull/625) will format files slightly differently.

ci(husky): fix husky v8

---

jest-setup.js
package.json
src/rules/at-rule-no-unknown/__tests__/index.js
src/rules/at-rule-no-unknown/index.js

Part of #652
This change also adds a test helper function to make testing multiline strings easier.

Fix `at-rule-no-unknown` end positions

---

.github/workflows/test.yml

Node.js 18 will be LTS soon. See also the release schedule:
https://github.com/nodejs/release#release-schedule

Add Node.js 18 to CI

---

src/rules/at-each-key-value-single-line/__tests__/index.js
src/rules/at-each-key-value-single-line/index.js

Part of #652
See the following example to be reported:
```scss
@each $key in map-keys($font-weights) {
/*    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*    Use @each $key, $value in $map syntax instead of $value: map-get($map, $key)
*/
$value: map-get($font-weights, $key);
}
```

Fix `at-each-key-value-single-line` end positions

---

src/rules/operator-no-unspaced/__tests__/index.js
src/rules/operator-no-unspaced/index.js

operator-no-unspaced: make data uri regex less strict

---

src/rules/operator-no-unspaced/__tests__/index.js
src/utils/__tests__/isInsideFunctionCall.test.js
src/utils/sassValueParser/index.js

operator-no-unspaced: add support for :has

---

src/rules/function-no-unknown/__tests__/index.js
src/rules/function-no-unknown/index.js

function-no-unknown: add support for @use

---

README.md
src/rules/function-no-unknown/README.md

This PR fixes just Markdown documents.

Fix incorrect links to `function-no-unknown` on Stylelint website

---

CHANGELOG.md
src/rules/function-disallowed-list/README.md
src/rules/function-disallowed-list/__tests__/index.js
src/rules/function-disallowed-list/index.js
src/rules/index.js

Add function-disallowed-list rule

---

CHANGELOG.md
README.md
src/rules/function-calculation-no-interpolation/README.md
src/rules/function-calculation-no-interpolation/__tests__/index.js
src/rules/function-calculation-no-interpolation/index.js
src/rules/index.js

Add function-calculation-no-interpolation rule

---

CHANGELOG.md
README.md
src/rules/at-use-no-redundant-alias/README.md
src/rules/at-use-no-redundant-alias/__tests__/index.js
src/rules/at-use-no-redundant-alias/index.js
src/rules/index.js

Add at-use-no-redundant-alias rule

---

CHANGELOG.md
src/rules/at-root-no-redundant/README.md
src/rules/at-root-no-redundant/__tests__/index.js
src/rules/at-root-no-redundant/index.js
src/rules/index.js

Add at-root-no-redundant rule

---

package-lock.json
package.json

#847 introduced a dependency on `known-css-properties` but didn't declare that in `package.json`

fix: add missing `known-css-properties` dependency

---

src/utils/parseSelector.js

Without this, I believe parse errors are being treated as warnings by `stylelint`. Updating this to match e.g. the [`parseSelector`](https://github.com/stylelint/stylelint/blob/74425d19a58449471498a83da519346290defee5/lib/utils/parseSelector.js#L16) function in `stylelint` causes them to be treated as errors.
- `git clone git@github.com:wlewis-formative/stylelint-scss-min-repro.git`
- Run `npm lint`
- Run `echo $?`
The exit code is `0`, even though errors were reported:
```shell
$ npm run lint
> stylelint-scss-min-repro@0.0.1 lint
> stylelint Bad.tsx
Bad.tsx
4:3  ✖  Cannot parse selector
1 problem (1 error, 0 warnings)
$ echo $?
0
```
This issue occurs because `postcss-styled-syntax` is parsing inline comments as selectors instead of reporting an error. The error is only discovered later …

Add `stylelintType: "parseError"` when `parseSelector` fails

---

src/rules/at-root-no-redundant/__tests__/index.js
src/rules/at-root-no-redundant/index.js

Fix false positive of redundant `@at-root` in selector list. 
This example is identified as redundant, even though @at-root is useful for the second selector `.a#{&}b `.
```
@at-root .c &,
.a#{&}b {
color: black;
}
```
Here's a [SCSS demo](https://sass-lang.com/playground/#eJwzNNRLrUjMLchJVajmUlBwSCzRLcrPL1HQS1SuVqvVS9IBCuolK6gp6KWAFYBAcn5OfpGVQlJOYnK2NVCsFoiJUV6aClFdCwAwQx5O) with examples.

Check selector list for parent selectors in `at-root-no-redundant`

---

src/rules/at-rule-no-unknown/index.js
src/rules/comment-no-empty/index.js
src/rules/function-no-unknown/index.js

Since Stylelint 16.0.0, the `stylelint.rules` object has `Promise` values. See the [migration guide](https://stylelint.io/migration-guide/to-16#changed-nodejs-api-stylelintrules-object).
Currently, this breaking change causes a `TypeError` in `stylelint-scss` because a few rules depend on `stylelint.rules` to construct rule messages.
This Pull Request removes the dependency to avoid the error.
To confirm compatibility with Stylelint 16.0.0, run:
```shell
npm i 'stylelint@latest'
NODE_OPTIONS=--experimental-vm-modules npm t
```
Ref #895
---
Another way to check the changed rules' messages:
`.stylelintrc.json`:
```json
{
"customSyntax": "postcss-scss",
"plugins": ["./src/index.js"],
"rules": {
"scss/at-rule-no-unknown": true,
"scss/comment-no-empty": true,
"scss/function-no-unknown": true
} …
```

Fix compatibility with Stylelint 16.0.0

---

src/rules/at-import-partial-extension/__tests__/index.js
src/rules/at-import-partial-extension/index.js

Fix `at-import-partial-extension` end positions

---

src/rules/at-mixin-pattern/__tests__/index.js
src/rules/at-mixin-pattern/index.js

Fix `at-mixin-pattern` end positions

---

src/rules/dimension-no-non-numeric-values/__tests__/index.js
src/rules/dimension-no-non-numeric-values/index.js

Fix `dimension-no-non-numeric-values` end positions

---

src/rules/function-color-relative/__tests__/index.js
src/rules/function-color-relative/index.js

Fix `function-color-relative` end positions

---

src/rules/load-no-partial-leading-underscore/__tests__/index.js
src/rules/load-no-partial-leading-underscore/index.js

Fix `load-no-partial-leading-underscore` end positions

---

src/rules/at-mixin-argumentless-call-parentheses/__tests__/index.js
src/rules/at-mixin-argumentless-call-parentheses/index.js

Fix `at-mixin-argumentless-call-parentheses` end positions

---

src/rules/at-mixin-parentheses-space-before/__tests__/index.js
src/rules/at-mixin-parentheses-space-before/index.js

Fix `at-mixin-parentheses-space-before` end positions

---

src/rules/double-slash-comment-inline/__tests__/index.js
src/rules/double-slash-comment-inline/index.js

Fix `double-slash-comment-inline` end positions

---

src/rules/operator-no-newline-before/__tests__/index.js
src/rules/operator-no-newline-before/index.js

Fix `operator-no-newline-before` end positions

---

src/rules/at-function-named-arguments/__tests__/index.js
src/rules/at-function-named-arguments/index.js
src/utils/__tests__/parseFunctionArguments.js
src/utils/parseFunctionArguments.js

Part of #652
This PR changes the `parseFunctionArguments()` utility, which is used only by the `at-function-named-arguments` rule.

Fix `at-function-named-arguments` end positions

---

src/rules/at-mixin-named-arguments/__tests__/index.js
src/rules/at-mixin-named-arguments/index.js
src/utils/__tests__/parseFunctionArguments.js
src/utils/parseFunctionArguments.js

Part of #652
Note: This PR uses the same utility (`parseFunctionArguments()`) as #939.

Fix `at-mixin-named-arguments` end positions

---

src/rules/property-no-unknown/__tests__/index.js
src/rules/property-no-unknown/index.js

Fix: `scss/property-no-unknown` is not recognizing more than two-level nested properties.
E.g.
```
background: {
position: {
x: left;
}
}
```
compiles to: `background-position-x: left;`. This is a [valid property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x).
However, it's currently raising the following error: `Unexpected unknown property "position-x" (scss/property-no-unknown)`.

property-no-unknown for deeper nested properties

---

CHANGELOG.md
package.json
src/rules/function-calculation-no-interpolation/__tests__/index.js
src/rules/function-calculation-no-interpolation/index.js

In the example case `--test: calc(#{$c} + 1);` , `#{$c}`  is mistakenly identified as an error. Interpolation is used in SassScript to inject dynamic values into a [CSS custom property](https://sass-lang.com/documentation/style-rules/declarations/#custom-properties). This allows interpolation when declaring CSS variables.

Allow calc function interpolation when declaring CSS custom properties.

---

src/rules/no-unused-private-members/__tests__/index.js
src/rules/no-unused-private-members/index.js

Refactor variable search to match regex in atRules params and declaration values. This improves findings reliability by eliminating the need to list all edge cases.

Refactor variable search in `no-unused-private-members`.

---

src/rules/no-unused-private-members/__tests__/index.js
src/rules/no-unused-private-members/index.js

no-unused-private-members treats hyphens and underscores as equals

---

src/rules/at-import-partial-extension-allowed-list/__tests__/index.js
src/rules/no-global-function-names/__tests__/index.js
src/rules/no-global-function-names/index.js
src/utils/getAtRuleParams.js

Support at-rules in `no-global-function-names`

---

src/rules/at-mixin-no-risky-nesting-selector/README.md
src/rules/at-mixin-no-risky-nesting-selector/__tests__/index.js
src/rules/at-mixin-no-risky-nesting-selector/index.js
src/rules/index.js

Add at-mixin-no-risky-nesting-selector rule.

---

src/rules/operator-no-unspaced/__tests__/index.js
src/rules/operator-no-unspaced/index.js

operator-no-unspaced: ignore operators inside @scope

---

package-lock.json
package.json
src/rules/partial-no-import/__tests__/index.js
src/rules/partial-no-import/index.js

By this change, the `partial-no-import` rule message will be properly associated with the rule name. See the examples below:
Before:
```sh-session
$ echo '@import "file.scss"' | npx stylelint
<input css ZECpLj>
✖  The 'partial-no-import' rule won't work if linting in a code string without an actual file
✖ 1 problem (1 error, 0 warnings)
```
After:
```sh-session
$ echo '@import "file.scss"' | npx stylelint
<input css PE6AAM>
1:2  ✖  This rule won't work if linting in a code string without an actual file  scss/partial-no-import
✖ 1 problem (1 error, 0 warnings)
```
In addition, this change updates `jest-preset-stylelint` to use `testRule()` instead of `postcss`.
Because `testRule()` is closer to the actual use of `stylelint` and easier to avoid any potential troubles.
See …

Fix `partial-no-import` message to include more accurate rule name

---

src/rules/load-partial-extension/__tests__/index.js
src/rules/load-partial-extension/index.js

Follow-up to #998. Without the code change, these new tests are failing.

Fix false positive for mixins in `load-partial-extension`

---

src/utils/functions.js

It was added in Sass 1.78 (see https://sass-lang.com/documentation/modules/color/#channel). Using it without this PR causes [`function-no-unknown`](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown) to report it as unknown.

Add `color.channel` function

---

src/rules/selector-no-redundant-nesting-selector/__tests__/index.js
src/rules/selector-no-redundant-nesting-selector/index.js

selector-no-redundant-nesting-selector: Add support for Dart Sass deprecation

---

package-lock.json
package.json
src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/rules/declaration-property-value-no-unknown/index.js

Currently imported custom functions are being flagged as `Unknown value`.
E.g.
```scss
// foo.scss
@function one() {
@return 1;
}
```
```scss
// bar.scss
@import "foo";
.b {
margin: one(); // Unexpected unknown value "one(" for property "margin" (scss/declaration-property-value-no-unknown).
}
```
This change checks whether the function exists in the CSS syntax (see: https://github.com/mdn/data/blob/main/css/syntaxes.json). If it doesn't exist, the function is tagged as a custom function, therefore skipped.

Fix false positives for imported custom functions in `scss/declaration-property-value-no-unknown`

---

src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/utils/validateTypes.js

Update `isDollarVar()` to include explicit namespace variables in multi-line values.
E.g.
```scss
@use foo;
.b {
transition: background-color 0.3s 
foo.$bar; // isDollarVar('foo.$bar') == true
}
```

Include explicit namespace variables in isDollarVar()

---

src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/rules/declaration-property-value-no-unknown/index.js

In this example:
```scss
$acx-white: "#fff";
.b {
background: {
clip: padding-box;
color: $acx-white;
}
}
```
Both `padding-box` for `background-clip`, and `$acx-white` for `background-color` are being flagged as unknown values.

Fix false positives for nested properties in nested decls

---

src/rules/at-mixin-no-risky-nesting-selector/__tests__/index.js
src/rules/at-mixin-no-risky-nesting-selector/index.js
src/rules/at-root-no-redundant/index.js
src/rules/function-calculation-no-interpolation/index.js
src/rules/no-unused-private-members/index.js

All Stylelint rules and almost all rules in this project use error messages without a trailing punctuation mark. This pull request unifies all of these messages and removes trailing punctuation marks.

Unify rule messages

---

src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/rules/declaration-property-value-no-unknown/index.js

Strip multiline values before processing in `declaration-property-value-no-unknown`

Fix multiline value parsing in declaration-property-value-no-unknown

---

src/rules/no-global-function-names/index.js

Enables `round()` function in `no-global-function-names` since it's widely available https://developer.mozilla.org/en-US/docs/Web/CSS/round
Addresses #1080
Wasn't sure if any new tests were necessary for this PR. Please let me know if they are.

Allow CSS round() function

---

src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/rules/declaration-property-value-no-unknown/index.js

Allow functions from explicit namespaces within other functions in `declaration-property-value-no-unknown`

---

src/rules/declaration-property-value-no-unknown/__tests__/index.js
src/rules/declaration-property-value-no-unknown/index.js

Add support to Sass `rgba()` in `declaration-property-value-no-unknown`.

---

src/rules/double-slash-comment-whitespace-inside/__tests__/index.js
src/rules/double-slash-comment-whitespace-inside/index.js

This adds autofixing to the rule and fixes incorrect error locations:

Improve double-slash-comment-whitespace-inside
