src/rules/selector-no-redundant-parent/README.md, src/rules/selector-no-redundant-parent/__tests__/index.js, src/rules/selector-no-redundant-parent/index.js
Most of the tests are from https://github.com/brigade/scss-lint/blob/master/spec/scss_lint/linter/unnecessary_parent_reference_spec.rb
**Checklist**
=> Add selector-no-redundant-parent, closes #3

src/rules/extend-require-placeholder/README.md, src/rules/extend-require-placeholder/__tests__/index.js, src/rules/extend-require-placeholder/index.js
Many of the tests and descriptions are taken from:
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#placeholderinextend
=> Add extend-require-placeholder, closes #1

package.json, src/rules/dollar-variable-pattern/README.md, src/rules/dollar-variable-pattern/__tests__/index.js, src/rules/dollar-variable-pattern/index.js
=> Add `dollar-variable-pattern` rule

CHANGELOG.md, README.md, package.json, src/index.js, src/rules/index.js
=> Plugin interface, readme, changelog

README.md, package.json
Prepare version 1.0.0. 
I have released a "pre-release" if you want to test it out, just `npm i stylelint-scss@0.0.0-alpha.1`.
ping @davidtheclark @jeddy3 @dryoma Let me know if there is anything that should be fixed before this plugin goes live.
=> Prepare version 1.0.0

CHANGELOG.md, README.md, src/rules/at-import-no-partial-extension/README.md, src/rules/at-import-no-partial-extension/__tests__/index.js, src/rules/at-import-no-partial-extension/index.js, src/rules/at-import-no-partial-leading-underscore/README.md, src/rules/at-import-no-partial-leading-underscore/__tests__/index.js, src/rules/at-import-no-partial-leading-underscore/index.js, src/rules/at-mixin-no-argumentless-call-parentheses/index.js, src/rules/index.js
Implements #19 
Decided to make it a PR from a separate branch as I believe there could be suggestions about the rules' names and functionality. If it's ok then I'll merge it (or you guys can, I don't mind :) )
=> at-import-path- rules

CHANGELOG.md, README.md, package.json, src/rules/index.js, src/rules/percent-placeholder-pattern/README.md, src/rules/percent-placeholder-pattern/__tests__/index.js, src/rules/percent-placeholder-pattern/index.js, src/utils/hasInterpolatingAmpersand.js, src/utils/index.js, src/utils/isStandardRule.js, src/utils/isStandardSelector.js, src/utils/parseSelector.js
=> New rule: percent-placeholder-pattern. Some utility functions

.travis.yml, CHANGELOG.md, package.json
Same as https://github.com/stylelint/stylelint/pull/1594 + changed Node.js version from 5 to 6 in .travis.yml
=> Require NodeJS 4.x LTS

CHANGELOG.md, package.json, src/rules/dollar-variable-pattern/README.md, src/rules/dollar-variable-pattern/__tests__/index.js, src/rules/dollar-variable-pattern/index.js
=> Variable pattern excludes

docs/examples/if-else.md
Swap duplicate rule out for correct rule in if/else docs
=> Fix if/else doc duplicate

docs/examples/if-else.md
=> Update if/else rule docs to use `rule-empty-line-before`

src/rules/at-else-closing-brace-newline-after/__tests__/index.js, src/rules/at-else-closing-brace-space-after/__tests__/index.js, src/rules/at-if-closing-brace-space-after/__tests__/index.js, src/rules/dollar-variable-empty-line-before/__tests__/index.js, src/rules/double-slash-comment-empty-line-before/__tests__/index.js, src/rules/double-slash-comment-inline/__tests__/index.js, src/rules/double-slash-comment-whitespace-inside/__tests__/index.js, src/rules/operator-no-unspaced/__tests__/index.js
=> Fix whitespace

src/rules/selector-no-redundant-nesting-selector/__tests__/index.js, src/rules/selector-no-redundant-nesting-selector/index.js
Fix: https://github.com/kristerkari/stylelint-scss/issues/112
=> Fixed: `selector-no-redundant-nesting-selector` now handle multiple nested selectors.

package.json
=> chore(package): update babel-preset-jest to version 22.0.3

package.json
=> chore(package): update jest-cli to version 22.0.4

README.md, src/rules/dollar-variable-default/README.md, src/rules/dollar-variable-default/__tests__/index.js, src/rules/dollar-variable-default/index.js, src/rules/index.js
=> dollar-variable-default rule #198

CHANGELOG.md, package.json
=> Add support for stylelint 9

.prettierignore, README.md, package-lock.json, package.json, src/rules/dollar-variable-colon-space-after/README.md, src/rules/dollar-variable-colon-space-after/__tests__/index.js, src/rules/dollar-variable-colon-space-after/index.js, src/utils/whitespaceChecker.js
~🚧 A work-in-progress — still need to add tests.~
Should address #195 
I think this should be ready; let me know what you think!
=> Add `at-least-one-space` opt to space after var colon rule (closes #195)

package.json
=> chore(package): update babel-preset-jest to version 22.4.1

src/rules/double-slash-comment-empty-line-before/__tests__/index.js, src/rules/double-slash-comment-empty-line-before/index.js
replaces #225 
Because RegExp construction from string is a mess 🤷‍♂️
=> Add autofix for double-slash-comment-empty-line-before

CHANGELOG.md, appveyor.yml, src/rules/at-function-named-arguments/__tests__/index.js, src/rules/at-function-named-arguments/index.js
=> at-function-named-arguments: ignore Sass maps

CHANGELOG.md, README.md, src/rules/index.js, src/rules/no-duplicate-dollar-variables/README.md, src/rules/no-duplicate-dollar-variables/__tests__/index.js, src/rules/no-duplicate-dollar-variables/index.js
=> Add no-duplicate-dollar-variables rule

src/rules/at-rule-no-unknown/README.md
=> Added instructions how to make the rule work

src/rules/operator-no-newline-after/__tests__/index.js, src/rules/operator-no-newline-after/index.js, src/rules/operator-no-newline-before/__tests__/index.js, src/rules/operator-no-newline-before/index.js
Find another little problem, need patch release :smile:
=> fix: handle non css syntaxes

README.md, src/rules/index.js, src/rules/no-dollar-variables/README.md, src/rules/no-dollar-variables/__tests__/index.js, src/rules/no-dollar-variables/index.js
=> Add no-dollar-variables rule

src/rules/operator-no-newline-after/__tests__/index.js, src/rules/operator-no-newline-before/__tests__/index.js, src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> make sure that operator* rules don't warn for unicode-range property

src/rules/no-duplicate-dollar-variables/README.md, src/rules/no-duplicate-dollar-variables/__tests__/index.js, src/rules/no-duplicate-dollar-variables/index.js
=> Add ignore options to no-duplicate-dollar-variables

package.json
=> chore(package): update postcss to version 7.0.1

CHANGELOG.md, src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: dont warn for relative url paths

src/rules/double-slash-comment-whitespace-inside/__tests__/index.js, src/utils/findCommentsInRaws.js
=> add thruthy test to findCommentsInRaws to avoid it throwing

src/rules/selector-nest-combinators/__tests__/index.js, src/rules/selector-nest-combinators/index.js
The messaging for selector-nest-combinators was not functioning as
expected, this commit should fix those issues.
=> [#300] - Messaging fix

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: improve handling of URLs

src/rules/selector-no-union-class-name/__tests__/index.js, src/rules/selector-no-union-class-name/index.js
Fixes #341
@nwoltman @pipopotamasu
=> selector-no-union-class-name: fix false positives for id/attr/pseudo

CHANGELOG.md, package-lock.json, package.json
=> Added: support for stylelint version 11

src/rules/selector-nest-combinators/__tests__/index.js, src/rules/selector-nest-combinators/index.js
=> selector-nest-combinators: ignore @keyframes

src/rules/at-rule-no-unknown/__tests__/index.js, src/rules/at-rule-no-unknown/index.js
This can probably replace #381.
See announcement of `@forward` and `@use` here: http://sass.logdown.com/posts/7858341-the-module-system-is-launched
=> Enable two new Sass at-rules: @forward and @use.

CHANGELOG.md, src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> operator-no-unspaced: ignore @forward and @use

CHANGELOG.md, src/rules/at-rule-conditional-no-parentheses/__tests__/index.js, src/rules/at-rule-conditional-no-parentheses/index.js
=> at-rule-conditional-no-parentheses: don't warn for function calls

jest-setup.js, package-lock.json, package.json, src/rules/declaration-nested-properties-no-divided-groups/__tests__/index.js, src/rules/declaration-nested-properties/__tests__/index.js, src/rules/no-duplicate-mixins/index.js, src/rules/operator-no-unspaced/__tests__/index.js, src/utils/__tests__/findCommentsInRaws.js, src/utils/__tests__/isInlineComment.js, src/utils/sassValueParser/index.js, src/utils/whitespaceChecker.js
* @babel/cli 7.7.0
* @babel/core 7.7.2
* @babel/preset-env 7.7.1
* babel-preset-jest 24.9.0
* coveralls 3.0.7
* eslint 6.6.0
* husky 3.1.0
* jest 24.9.0
* jest-cli 24.9.0
* lint-staged 9.4.3
* postcss 7.0.21
* prettier 1.19.1
* stylelint 12.0.0
Fixes #401
Closes #396 by superseding it
=> Update devDependencies and regenerate package-lock.json

jest-setup.js, package-lock.json, package.json, src/rules/at-else-closing-brace-newline-after/index.js, src/rules/at-function-named-arguments/index.js, src/rules/at-function-pattern/index.js, src/rules/at-if-closing-brace-newline-after/index.js, src/rules/at-import-partial-extension-blacklist/index.js, src/rules/at-import-partial-extension-whitelist/index.js, src/rules/at-mixin-pattern/index.js, src/rules/at-rule-conditional-no-parentheses/index.js, src/rules/at-rule-no-unknown/index.js, src/rules/dollar-variable-colon-newline-after/index.js, src/rules/dollar-variable-empty-line-before/index.js, src/rules/dollar-variable-no-missing-interpolation/index.js, src/rules/dollar-variable-pattern/index.js, src/rules/no-duplicate-dollar-variables/index.js, src/rules/percent-placeholder-pattern/index.js, src/utils/addEmptyLineBefore.js, src/utils/findCommentsInRaws.js, src/utils/hasInterpolatingAmpersand.js, src/utils/parseFunctionArguments.js, src/utils/whitespaceChecker.js
use the individual packages and replace the following methods with their native counterparts:
* assign
* head
* includes
* isUndefined
* repeat
* uniq
Fixes #399
=> Reduce lodash usage.

README.md
@kristerkari did you switch to dependabot? If not feel free to close this. I just noticed the badge was broken.
=> README.md: remove greenkeeper badge

.github/workflows/test.yml, package.json
Also, make use of the `jest` script consistently
Fixes #407
=> Change prepublish to prepublishOnly.

package.json
It's already in eslint-config-stylelint
Fixes #431
=> Remove eslint-plugin-sort-requires

src/utils/__tests__/hasInterpolation.test.js, src/utils/__tests__/isStandardSyntaxProperty.test.js, src/utils/__tests__/isStandardSyntaxSelector.test.js, src/utils/hasInterpolation.js, src/utils/hasLessInterpolation.js, src/utils/hasPsvInterpolation.js, src/utils/hasScssInterpolation.js, src/utils/hasTplInterpolation.js, src/utils/isStandardSelector.js, src/utils/isStandardSyntaxProperty.js, src/utils/isStandardSyntaxSelector.js
Split from #428 
**Should probably be merged after #428 and a rebase.**
=> Stop using private Stylelint code

src/rules/function-color-relative/__tests__/index.js, src/rules/function-color-relative/index.js
=> function-color-relative: handle filter property

src/rules/no-duplicate-dollar-variables/README.md, src/rules/no-duplicate-dollar-variables/__tests__/index.js, src/rules/no-duplicate-dollar-variables/index.js
https://github.com/kristerkari/stylelint-scss/issues/500
something to start off with regards to the raised request (still needs to add documentation in this case and add more tests)
will continue once feedback is provided :)
=> add `ignoreDefaults` options on no duplicate dollar var rule

src/rules/dollar-variable-pattern/README.md
Provide better examples and formatting / usage instructions in the form of comment blocks like ESLint. See: https://eslint.org/docs/rules/lines-between-class-members#options
Ensure example formatting is consistent throughout README doc.
=> Eslint-like examples for dollar-variable-pattern

src/rules/dimension-no-non-numeric-values/__tests__/index.js, src/rules/dimension-no-non-numeric-values/index.js
=> dimension-no-non-numeric-values: fix error thrown with unitless interpolation

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: fix false positive

src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> operator-no-unspaced: don't check operators from data URIs

README.md, src/rules/at-use-no-unnamespaced/README.md, src/rules/at-use-no-unnamespaced/__tests__/index.js, src/rules/at-use-no-unnamespaced/index.js, src/rules/index.js
Closes https://github.com/stylelint-scss/stylelint-scss/issues/565
=> Implement the at-use-no-unnamespaced rule

README.md, src/rules/dollar-variable-no-namespaced-assignment/README.md, src/rules/dollar-variable-no-namespaced-assignment/__tests__/index.js, src/rules/dollar-variable-no-namespaced-assignment/index.js, src/rules/index.js
=> Implement the dollar-variable-no-namespaced-assignment rule

src/rules/media-feature-value-dollar-variable/__tests__/index.js, src/rules/media-feature-value-dollar-variable/index.js
=> media-feature-value-dollar-variable: support @use

src/rules/function-quote-no-quoted-strings-inside/__tests__/index.js, src/rules/function-quote-no-quoted-strings-inside/index.js
=> function-quote-no-quoted-strings-inside: improve autofix

CONTRIBUTING.md, README.md, src/rules/no-global-function-names/README.md
=> docs: fix broken links

.babelrc.json, .eslintrc.json, .lintstagedrc.json, .prettierrc.json, jest.config.js, package.json
@kristerkari I know you might not prefer this solution but our package.json keeps growing and it's harder to find things.
=> Move things outside of package.json

.github/workflows/test.yml
=> CI: remove `--runInBand`

src/rules/at-root-no-redundant/__tests__/index.js, src/rules/at-root-no-redundant/index.js
Add fix to `at-root-no-redundant` by removing the redundant `@at-root` rule from the node string and parsing / appending the new node.
=> Add `--fix` to `at-root-no-redundant`.

src/rules/at-root-no-redundant/__tests__/index.js, src/rules/at-use-no-redundant-alias/__tests__/index.js, src/rules/at-use-no-redundant-alias/index.js
Add fix to `at-use-no-redundant-alias` by removing the redundant alias from the node string and parsing / appending the new node.
=> Add `--fix` to `at-use-no-redundant-alias`

src/rules/at-root-no-redundant/__tests__/index.js, src/rules/at-root-no-redundant/index.js
=> Check if all selectors followed by @at-root include '&' outside interpolation

README.md, src/rules/at-import-no-partial-leading-underscore/index.js, src/rules/index.js, src/rules/load-no-partial-leading-underscore/README.md, src/rules/load-no-partial-leading-underscore/__tests__/index.js, src/rules/load-no-partial-leading-underscore/index.js
=> Add `load-no-partial-leading-underscore` rule.

src/rules/block-no-redundant-nesting/__tests__/index.js, src/rules/block-no-redundant-nesting/index.js
=> Improve `block-no-redundant-nesting` autofix

.github/workflows/lint.yml, .github/workflows/test.yml, package-lock.json, package.json, src/rules/at-rule-no-unknown/index.js, src/rules/function-no-unknown/index.js
=> Support Stylelint 16

src/rules/at-extend-no-missing-placeholder/__tests__/index.js, src/rules/at-extend-no-missing-placeholder/index.js
=> Fix `at-extend-no-missing-placeholder` end positions

src/rules/at-function-pattern/__tests__/index.js, src/rules/at-function-pattern/index.js
=> Fix `at-function-pattern` end positions

src/rules/at-if-no-null/__tests__/index.js, src/rules/at-if-no-null/index.js
=> Fix `at-if-no-null` end positions

src/rules/at-root-no-redundant/__tests__/index.js, src/rules/at-root-no-redundant/index.js
=> Fix `at-root-no-redundant` end positions

src/rules/at-use-no-unnamespaced/__tests__/index.js, src/rules/at-use-no-unnamespaced/index.js
=> Fix `at-use-no-unnamespaced` end positions

src/rules/dollar-variable-no-missing-interpolation/__tests__/index.js, src/rules/dollar-variable-no-missing-interpolation/index.js
=> Fix `dollar-variable-no-missing-interpolation` end positions

src/rules/dollar-variable-pattern/__tests__/index.js, src/rules/dollar-variable-pattern/index.js
=> Fix `dollar-variable-pattern` end positions

src/rules/function-calculation-no-interpolation/__tests__/index.js, src/rules/function-calculation-no-interpolation/index.js
=> Fix `function-calculation-no-interpolation` end positions

src/rules/function-disallowed-list/__tests__/index.js, src/rules/function-disallowed-list/index.js
=> Fix `function-disallowed-list` end positions

src/rules/map-keys-quotes/__tests__/index.js, src/rules/map-keys-quotes/index.js
=> Fix `map-keys-quotes` end positions

src/rules/no-dollar-variables/__tests__/index.js, src/rules/no-dollar-variables/index.js
=> Fix `no-dollar-variables` end positions

src/rules/no-duplicate-dollar-variables/__tests__/index.js, src/rules/no-duplicate-dollar-variables/index.js
=> Fix `no-duplicate-dollar-variables` end positions

src/rules/no-duplicate-mixins/__tests__/index.js, src/rules/no-duplicate-mixins/index.js
=> Fix `no-duplicate-mixins` end positions

src/rules/no-global-function-names/__tests__/index.js, src/rules/no-global-function-names/index.js
=> Fix `no-global-function-names` end positions

src/rules/percent-placeholder-pattern/__tests__/index.js, src/rules/percent-placeholder-pattern/index.js
=> Fix `percent-placeholder-pattern` end positions

src/rules/selector-nest-combinators/__tests__/index.js, src/rules/selector-nest-combinators/index.js
Part of #652
This change also fixes duplicate reported lint problems.
=> Fix `selector-nest-combinators` end positions

src/rules/selector-no-redundant-nesting-selector/__tests__/index.js, src/rules/selector-no-redundant-nesting-selector/index.js
=> Fix `selector-no-redundant-nesting-selector` end positions

src/rules/selector-no-union-class-name/__tests__/index.js, src/rules/selector-no-union-class-name/index.js
=> Fix `selector-no-union-class-name` end positions

src/rules/at-else-empty-line-before/__tests__/index.js, src/rules/at-else-empty-line-before/index.js
=> Fix `at-else-empty-line-before` end positions

src/rules/at-else-if-parentheses-space-before/__tests__/index.js, src/rules/at-else-if-parentheses-space-before/index.js
=> Fix `at-else-if-parentheses-space-before` end positions

src/rules/at-function-parentheses-space-before/__tests__/index.js, src/rules/at-function-parentheses-space-before/index.js
=> Fix `at-function-parentheses-space-before` end positions

src/rules/at-rule-conditional-no-parentheses/__tests__/index.js, src/rules/at-rule-conditional-no-parentheses/index.js
=> Fix `at-rule-conditional-no-parentheses` end positions

src/rules/declaration-nested-properties-no-divided-groups/__tests__/index.js, src/rules/declaration-nested-properties-no-divided-groups/index.js
=> Fix `declaration-nested-properties-no-divided-groups` end positions

src/rules/function-quote-no-quoted-strings-inside/__tests__/index.js, src/rules/function-quote-no-quoted-strings-inside/index.js
=> Fix `function-quote-no-quoted-strings-inside` end positions

src/rules/function-unquote-no-unquoted-strings-inside/__tests__/index.js, src/rules/function-unquote-no-unquoted-strings-inside/index.js
=> Fix `function-unquote-no-unquoted-strings-inside` end positions

src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> Fix `operator-no-unspaced` end positions

CHANGELOG.md, README.md, package-lock.json, package.json, src/rules/index.js, src/rules/no-unused-private-members/README.md, src/rules/no-unused-private-members/__tests__/index.js, src/rules/no-unused-private-members/index.js
=> Add no-unused-private-members rule

src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> operator-no-unspaced: fix data uri in background shorthand

src/rules/at-rule-conditional-no-parentheses/__tests__/index.js, src/rules/at-rule-conditional-no-parentheses/index.js
=> at-rule-conditional-no-parentheses: remove extra autofix space

src/rules/function-no-unknown/__tests__/index.js, src/rules/function-no-unknown/index.js, src/utils/__tests__/hasInterpolation.test.js, src/utils/hasLessInterpolation.js, src/utils/hasPsvInterpolation.js, src/utils/hasScssInterpolation.js
=> function-no-unknown: handle functions inside interpolation

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: fix function calls inside interpolation

src/rules/at-function-named-arguments/__tests__/index.js, src/rules/at-function-named-arguments/index.js
=> at-function-named-arguments: handle interpolation in ignored fn names

src/rules/function-no-unknown/__tests__/index.js, src/rules/function-no-unknown/index.js
=> function-no-unknown: fix falsely reported CSS functions

src/rules/no-duplicate-mixins/__tests__/index.js, src/rules/no-duplicate-mixins/index.js
=> no-duplicate-mixins: allow using same name in different scope

src/rules/no-unused-private-members/__tests__/index.js, src/rules/no-unused-private-members/index.js
=> Fix changes from hyphen to underscore in debug message

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: handle Tailwind CSS direct children styling

src/rules/selector-no-redundant-nesting-selector/__tests__/index.js, src/rules/selector-no-redundant-nesting-selector/index.js
=> selector-no-redundant-nesting-selector: handle pseudo selectors

src/rules/at-mixin-no-risky-nesting-selector/__tests__/index.js, src/rules/at-mixin-no-risky-nesting-selector/index.js
=> Fix false positives in `at-mixin-no-risky-nesting-selector`.

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: handle variables with unary negation

README.md, src/rules/at-import-partial-extension/index.js, src/rules/index.js, src/rules/load-partial-extension/README.md, src/rules/load-partial-extension/__tests__/index.js, src/rules/load-partial-extension/index.js
=> Add `load-partial-extension` and deprecate `at-import-partial-extension`.

src/rules/property-no-unknown/__tests__/index.js, src/rules/property-no-unknown/index.js
=> Add property-no-unknown support for nested declarations

src/rules/operator-no-unspaced/__tests__/index.js, src/utils/sassValueParser/index.js
=> operator-no-unspaced: fix false positives with comparison operators

src/rules/function-quote-no-quoted-strings-inside/index.js, src/rules/function-unquote-no-unquoted-strings-inside/__tests__/index.js, src/rules/function-unquote-no-unquoted-strings-inside/index.js
=> function-unquote-no-unquoted-strings-inside: fix broken autofix

package-lock.json, package.json, src/rules/declaration-property-value-no-unknown/__tests__/index.js, src/rules/declaration-property-value-no-unknown/index.js
- Support first-class operators.
- Support SCSS variables as arguments in nested functions.
=> Fix false positives in `declaration-property-value-no-unknown` for dollar vars and operators.

package-lock.json, package.json, src/rules/declaration-property-value-no-unknown/__tests__/index.js, src/rules/declaration-property-value-no-unknown/index.js
Mirrors stylelint's PR: https://github.com/stylelint/stylelint/pull/7993
=> Bump css-tree from 2.3.1 to 3.0.0

src/rules/declaration-property-value-no-unknown/__tests__/index.js, src/rules/declaration-property-value-no-unknown/index.js, src/utils/getDeclarationValue.js
Mirrors stylelint's PR: https://github.com/stylelint/stylelint/pull/8003
=> Fix declaration-property-value-no-unknown reported ranges and message

README.md, src/rules/function-color-channel/README.md, src/rules/function-color-channel/__tests__/index.js, src/rules/function-color-channel/index.js, src/rules/function-color-relative/__tests__/index.js, src/rules/function-color-relative/index.js, src/rules/index.js
=> Add new `function-color-channel` rule

src/rules/no-global-function-names/__tests__/index.js
A follow up for #1097
Closes #1080
=> no-global-function-names: add unit test for CSS round

src/rules/index.js, src/rules/no-duplicate-load-rules/README.md, src/rules/no-duplicate-load-rules/__tests__/index.js, src/rules/no-duplicate-load-rules/index.js
=> Add `no-duplicate-load-rules` rule.

src/rules/no-duplicate-load-rules/__tests__/index.js, src/rules/no-duplicate-load-rules/index.js
=> Check load duplicate rules by atRule name

src/rules/at-use-no-redundant-alias/__tests__/index.js, src/rules/at-use-no-redundant-alias/index.js
=> Fix false negative for single quotes in scss/at-use-no-redundant-alias.

src/rules/operator-no-unspaced/__tests__/index.js, src/rules/operator-no-unspaced/index.js
=> operator-no-unspaced: don't check Tailwind Directives
